services:
  nginx:
    build:
      context: ./nginx
    image: elensant/nginx:dev
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-nginx-db
    depends_on:
      db:
        condition: service_healthy
  node:
    build:
      context: ./node
    image: elensant/node:dev
    container_name: node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - node-nginx-db
    depends_on:
      db:
        condition: service_healthy  
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: elen 
    networks:
      - node-nginx-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
      - ./mysql:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  node-nginx-db:
    driver: bridge