# Usar uma imagem base do Nginx
FROM nginx:1.15.0-alpine

# Definir o diretório de trabalho (opcional)
WORKDIR /app

# Copiar o arquivo de configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Instalar o Vim (opcional)
RUN apk update && apk add vim

# Comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]
