# Usar uma imagem Node.js como base
FROM node:15 AS build

# Definir o diretório de trabalho
WORKDIR /usr/src/app

# Copiar os arquivos package.json e package-lock.json
COPY package*.json ./

# Instalar dependências de produção
RUN npm install --production

# Copiar o restante do código da aplicação
COPY . .

# Expor a porta 3000
EXPOSE 3000

# Comando para iniciar a aplicação Node.js
CMD ["node", "./src/app"]